### ISSUE TITLE
Problema no path em ambientes Linux durante a criação dos Resources

### ISSUE THREAD

**Issue by franklinsales** [marcusvbda/vstack#2]
**O que eu tentei fazer:**  
Eu estava criando um resource no Ubuntu, mas creio que o path da criação dos diretórios e arquivos não foi executado no padrão Unix "/" e isso causo erro durante a criação.

**Erro:**  
![Imagem Exemplo do Erro](https://user-images.githubusercontent.com/2087195/82077903-936f9880-96b6-11ea-82db-bd7d2debe054.png)

**Comment by marcusvbda** [comment]
resolvido
